project_id = "ucmgnwnwapchxdomupsz"

[functions.user-admin]
verify_jwt = false

[functions.bootstrap-master]
verify_jwt = false

[functions.enviar-notificacao]
verify_jwt = false

[functions.lembrete-plantoes]
verify_jwt = false

[functions.auth-sso]
verify_jwt = false

[functions.auth-sso-logout]
verify_jwt = false

[functions.auth-refresh]
verify_jwt = false